### ISSUE TITLE
mouse pointer move out of the field

### ISSUE THREAD

**Issue by eugenner** [Dev1an/Trackpad-Drummer#1]
Sometimes, during the playing if you make not just touch but touch and little move your finger, mouse pointer goes out of application field after time. And you should place it back because It breaks the playing process. May be it is possible to add some hot-keys combination to enable/disable pointer...

**Comment by Dev1an** [comment]
I added this feature in 34f3d865a5fadddd3d604ccb1fe1a1536d021435
Download it at: https://github.com/Dev1an/Trackpad-Drummer/releases/latest
