### ISSUE TITLE
Locking mouse

### ISSUE THREAD

**Issue by eugenner** [Dev1an/Trackpad-Drummer#2]
Locking is working but when you start to touch lower part of pad, pointer locks and unlocks after each touching.

**Comment by Dev1an** [comment]
Good catch, can you try the new version ([v1.1.1](https://github.com/Dev1an/Trackpad-Drummer/releases/tag/v1.1.1))?

**Comment by eugenner** [comment]
Oh, now I can’t compile the project, I have never use xcode before and now lost the page in editor where I have to choose something like license…

I see such error: 
Code Signing Error: No account for team "7TD9A665TC". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "7TD9A665TC" with a private key was found.


I know that I have to put there my own certificate or something but again - don’t know how to open that page in xcode :-))

Can you help me?

**Comment by Dev1an** [comment]
Go to https://github.com/Dev1an/Trackpad-Drummer/releases/tag/v1.1.1 and click on “Magic.Drumpad.app.zip”. This should download the new version of the app.

**Comment by eugenner** [comment]
Aha. Nice. Now it’s working good and just like app so I need no to start xcode.

I just started to play real drums and have to training, so your application is the best for me.

Thank you! :-)

And now the next question: is it possible to change sound samples? ;-)

**Comment by Dev1an** [comment]
I am currently studying and don't have much time to program... But I was thinking (#3) about making the application output MIDI signals so that it can be used in any music program (like for example Garageband). This would allow you to try out different samples.

If I were to make this and put it on the app store for, lets say, $5, would you consider buying this?

**Comment by eugenner** [comment]
> On 22 Jan 2018, at 15:13, Damiaan Dufaux <notifications@github.com> wrote:
> 
> I am currently studying and don't have much time to program... But I was thinking (#3 <https://github.com/Dev1an/Trackpad-Drummer/issues/3>) about making the application output MIDI signals so that it can be used in any music program (like for example Garageband). This would allow you to try out different samples.
> 

That sounds interesting. I have to install Garageband again, because I deleted it when I was out of space on my mac.


> If I were to make this and put it on the app store for, lets say, $5, would you consider buying this?
> 

At first I was looking on the app store and found nothing, and after I have found your open source solution. 
So probably it is reasonable price because you have simple but original product. 

And in real, for studying playing drums, especially for beginners, it is important to have a metronome, like this one https://www.flutetunes.com/metronome/ <https://www.flutetunes.com/metronome/>, with which I’m trying to play right now :-)


Regards, 
Eugene.

**Comment by Dev1an** [comment]
Thanks a lot for your valuable input and feedback!
I will let you know when a new version of the app comes out 😉

**Comment by Dev1an** [comment]
@eugenner: I added some basic MIDI support in [version 1.2](https://github.com/Dev1an/Trackpad-Drummer/releases/tag/1.2)

**Comment by Dev1an** [comment]
To enable MIDI output: go to Preferences and click
 - [x] Send MIDI notes
